openapi: 3.0.0
info:
  title: To-Do-List
  description: A list of errands and other tasks
  contact:
    name: Misha
    url: localhost/todolist.ru
    email: misha-tur@yandex.ru
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/S0GGeR/To-Do-List/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: items
  description: Everything about your Items
paths:
  /items:
    get:
      tags:
      - items
      summary: Reload list of items
      operationId: rldlist
      parameters:
      - name: List
        in: query
        description: List of items that need to be print
        required: true
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
            default: reload
            enum:
            - reload
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/items'
        400:
          description: Something wrong
    put:
      tags:
      - items
      summary: Edit a item in the list of items
      operationId: editItem
      requestBody:
        $ref: '#/components/requestBodies/items'
      responses:
        200:
          description: Everything is ok!
        405:
          description: Invalid input
    post:
      tags:
      - items
      summary: Add a new item to the list of items
      operationId: addItem
      requestBody:
        $ref: '#/components/requestBodies/items'
      responses:
        200:
          description: Everything is ok!
        405:
          description: Invalid input
    delete:
      tags:
      - items
      summary: Deletes a item
      operationId: deleteItem
      parameters:
      - name: itemBody
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: itemId
        in: query
        description: Item id to delete
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: Item was successfully remote
        400:
          description: Invalid ID supplied
        404:
          description: Item not found
components:
  schemas:
    items:
      required:
      - id
      - text
      type: object
      properties:
        id:
          type: integer
          format: int64
        text:
          type: string
          example: Call for your mother
  requestBodies:
    items:
      description: Item object that needs to be added to the items
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/items'
      required: true
